"""
profile_discovery_agent.py
──────────────────────────
LangGraph-based Profile Discovery Agent.
Discovers relevant LinkedIn profiles via web search, scores them with Gemini,
and adds them to memory.db after human approval (or auto-adds above threshold).

Workflow:
  search → extract_candidates → score_candidates → human_gate → add_approved
"""

import os
import re
import sys
import json
import time
import argparse
from typing import List, Dict, Optional, TypedDict
from pydantic import BaseModel, Field

from logger import setup_logger
from analyzer import get_llm, AKSH_INTEREST_PROFILE
from memory import (
    get_all_persons, add_person, username_from_url, name_to_username, build_profile_url
)
from retry import with_retry

# Initialize logger
log = setup_logger("discovery_agent")

# ── State Graph State Definition ──────────────────────────────────────────────

class DiscoveryState(TypedDict):
    search_queries: List[str]
    raw_search_results: List[Dict]      # keys: title, url, snippet
    candidate_profiles: List[Dict]      # keys: name, username, profile_url, headline, snippet
    scored_candidates: List[Dict]       # keys: name, username, profile_url, headline, snippet, relevance_score, matched_interests, skip_reason
    approved_profiles: List[Dict]       # keys: name, username, profile_url, note
    added_count: int
    dry_run: bool
    auto_add: bool
    threshold: int
    errors: List[str]


# ── Pydantic Schemas for AI ───────────────────────────────────────────────────

class QueryList(BaseModel):
    """List of search queries generated by AI to find relevant LinkedIn profiles."""
    queries: List[str] = Field(
        description="3-5 highly targeted Google search queries using operators (like site:linkedin.com/in) and keywords."
    )


class CandidateEvaluation(BaseModel):
    """AI evaluation of a potential LinkedIn profile candidate."""
    name: str = Field(description="The person's full name, or best guess from context. If not found, use N/A.")
    headline: str = Field(description="The person's headline or job title, or best guess. If not found, use N/A.")
    relevance_score: int = Field(
        description="Relevance score from 1-10 based on Akshu's interest areas. 7+ is relevant and has actionable depth.",
        ge=1,
        le=10
    )
    matched_interests: List[str] = Field(
        description="List of specific interest areas this person matches (e.g., ['LangGraph', 'agentic AI'])."
    )
    skip_reason: str = Field(
        description="Brief explanation of why this profile was scored high or low. If relevance_score >= 7, write 'High potential candidate'.",
    )


# ── LangGraph Nodes ───────────────────────────────────────────────────────────

def search_node(state: DiscoveryState) -> DiscoveryState:
    """Generate search queries and query web search API (Tavily or DuckDuckGo fallback)."""
    log.info("[search_node] Generating search queries...")
    print("\n[->] Generating search queries using Gemini...")

    llm = get_llm()
    structured_llm = llm.with_structured_output(QueryList, method="json_schema")

    prompt = f"""
    You are generating search queries to discover high-quality LinkedIn profiles of builders, 
    engineers, researchers, and practitioners that Akshu Grewal should track.
    
    Akshu's interest profile:
    {AKSH_INTEREST_PROFILE}
    
    Generate 4 distinct search queries.
    Rules for queries:
    1. They MUST use search operators like `site:linkedin.com/in` or `"linkedin.com/in"` to target individual profile pages.
    2. They must contain modern keywords related to Akshu's interests (e.g., "LangGraph", "agentic AI", "multi-agent systems", "RAG pipelines", "Google ADK", "browser agents").
    3. They should avoid generic AI terms like "AI enthusiast" or "AI influencer" to keep the signal-to-noise ratio high.
    
    Example queries:
    - `site:linkedin.com/in "LangGraph" "engineer"`
    - `site:linkedin.com/in "agentic AI" "developer"`
    - `site:linkedin.com/in "Google ADK" OR "Gemini API" builder`
    """

    try:
        query_list: QueryList = with_retry(
            lambda: structured_llm.invoke(prompt),
            retries=3,
            base_delay=5.0,
            label="Gemini Query Generation"
        )
        queries = query_list.queries
        log.info(f"[search_node] Generated queries: {queries}")
        print(f"    Generated queries:")
        for q in queries:
            print(f"      - {q}")
    except Exception as e:
        log.error(f"[search_node] Query generation failed: {e}")
        # Fail safe fallback queries
        queries = [
            'site:linkedin.com/in "LangGraph" engineer',
            'site:linkedin.com/in "agentic AI" developer',
            'site:linkedin.com/in "Google ADK" builder',
            'site:linkedin.com/in "RAG pipelines" developer'
        ]
        print(f"    Query generation failed. Using fallback queries.")

    raw_results = []
    tavily_key = os.getenv("TAVILY_API_KEY")

    if tavily_key and tavily_key != "your_tavily_api_key_here":
        # Use Tavily
        log.info("[search_node] Using Tavily for search")
        print("\n[->] Querying Tavily Search API...")
        try:
            from tavily import TavilyClient
            client = TavilyClient(api_key=tavily_key)
            for q in queries:
                log.info(f"[search_node] Querying Tavily: {q}")
                response = client.search(query=q, max_results=5, include_answer=False)
                for r in response.get("results", []):
                    raw_results.append({
                        "title": r.get("title", ""),
                        "url": r.get("url", ""),
                        "snippet": r.get("content", "")
                    })
                time.sleep(1.0) # rate limit safety
        except Exception as e:
            log.error(f"[search_node] Tavily search failed: {e}")
            state["errors"].append(f"Tavily failed: {e}")
            tavily_key = None # trigger fallback below
    
    if not tavily_key or tavily_key == "your_tavily_api_key_here":
        # Fallback to DuckDuckGo
        log.info("[search_node] Falling back to DuckDuckGo search")
        print("\n[->] Querying DuckDuckGo Search (no API key needed)...")
        try:
            from duckduckgo_search import DDGS
            with DDGS() as ddgs:
                for q in queries:
                    log.info(f"[search_node] Querying DDG: {q}")
                    results = ddgs.text(q, max_results=5)
                    for r in results:
                        raw_results.append({
                            "title": r.get("title", ""),
                            "url": r.get("href") or r.get("link") or "",
                            "snippet": r.get("body") or r.get("snippet") or ""
                        })
                    time.sleep(1.0) # rate limit safety
        except Exception as e:
            log.error(f"[search_node] DDG search failed: {e}")
            state["errors"].append(f"DDG failed: {e}")

    state["search_queries"] = queries
    state["raw_search_results"] = raw_results
    return state


def extract_candidates_node(state: DiscoveryState) -> DiscoveryState:
    """Parse raw search results, extract LinkedIn profile URLs, and deduplicate against database."""
    log.info("[extract_candidates_node] Extracting candidate profiles...")
    print("\n[->] Extracting and deduplicating LinkedIn profiles...")

    raw_results = state["raw_search_results"]
    candidates = []
    seen_urls = set()

    # Get already tracked users to deduplicate
    try:
        existing_persons = get_all_persons(active_only=False)
        existing_usernames = {p["username"] for p in existing_persons}
    except Exception as e:
        log.error(f"[extract_candidates_node] Failed to load existing persons: {e}")
        existing_usernames = set()

    for item in raw_results:
        url = item.get("url", "")
        username = username_from_url(url)
        if not username:
            continue

        if username in existing_usernames:
            # Already tracked, skip
            continue

        if username in seen_urls:
            # Duplicate in current search results, skip
            continue

        seen_urls.add(username)

        # Parse name and headline from the search result title
        # LinkedIn titles usually look like: "First Last - Headline - Company | LinkedIn" or "First Last - Company | LinkedIn"
        title = item.get("title", "")
        title_clean = re.sub(r"\s*-\s*LinkedIn\s*", "", title, flags=re.IGNORECASE)
        title_clean = re.sub(r"\s*\|\s*LinkedIn\s*", "", title_clean, flags=re.IGNORECASE)
        
        parts = [p.strip() for p in title_clean.split("-")]
        name = parts[0] if parts else username
        headline = parts[1] if len(parts) > 1 else item.get("snippet", "")[:100]

        candidates.append({
            "name": name,
            "username": username,
            "profile_url": build_profile_url(username),
            "headline": headline,
            "snippet": item.get("snippet", "")
        })

    log.info(f"[extract_candidates_node] Found {len(candidates)} new candidates after deduplication.")
    print(f"    Found {len(candidates)} new profiles to score (deduplicated against existing DB).")
    
    state["candidate_profiles"] = candidates
    return state


def score_candidates_node(state: DiscoveryState) -> DiscoveryState:
    """Score each candidate profile based on their search result snippets using Gemini."""
    log.info("[score_candidates_node] Scoring candidates...")
    candidates = state["candidate_profiles"]
    
    if not candidates:
        log.info("[score_candidates_node] No candidates to score.")
        state["scored_candidates"] = []
        return state

    print(f"\n[->] Scoring {len(candidates)} candidates with Gemini...")

    llm = get_llm()
    structured_llm = llm.with_structured_output(CandidateEvaluation, method="json_schema")
    scored = []

    for i, candidate in enumerate(candidates, 1):
        print(f"  [{i}/{len(candidates)}] Evaluating: {candidate['name']} - {candidate['headline'][:40]}...")
        
        prompt = f"""
        Akshu's Interest Profile:
        {AKSH_INTEREST_PROFILE}
        
        ─────────────────────────────────────────
        CANDIDATE PROFILE TO EVALUATE:
        ─────────────────────────────────────────
        Suggested Name: {candidate['name']}
        LinkedIn Headline/Title: {candidate['headline']}
        Search Snippet / Biography Details:
        {candidate['snippet']}
        
        Analyze this person's profile details. Predict how relevant they are to Akshu's core interest areas.
        A score of 7+ means they are actively building, researching, or writing quality content about LangGraph, LangChain, multi-agent networks, RAG, Gemini API, or advanced AI engineering.
        Lower scores mean they are generic tech writers, influencers, job seekers, or work in unrelated fields.
        """

        try:
            eval_result: CandidateEvaluation = with_retry(
                lambda: structured_llm.invoke(prompt),
                retries=3,
                base_delay=5.0,
                label=f"Gemini Score Candidate {candidate['name']}"
            )
            
            scored.append({
                "name": eval_result.name if eval_result.name != "N/A" else candidate["name"],
                "username": candidate["username"],
                "profile_url": candidate["profile_url"],
                "headline": eval_result.headline if eval_result.headline != "N/A" else candidate["headline"],
                "snippet": candidate["snippet"],
                "relevance_score": eval_result.relevance_score,
                "matched_interests": eval_result.matched_interests,
                "skip_reason": eval_result.skip_reason
            })
            log.info(f"[score_candidates_node] Evaluated {candidate['name']}: score={eval_result.relevance_score}")
        except Exception as e:
            log.error(f"[score_candidates_node] Failed to evaluate candidate {candidate['name']}: {e}")
            # Safe fallback score
            scored.append({
                **candidate,
                "relevance_score": 5,
                "matched_interests": [],
                "skip_reason": f"Evaluation error: {e}"
            })
        
        time.sleep(1.0) # rate limit safety

    # Sort candidates by relevance score descending
    scored.sort(key=lambda x: x["relevance_score"], reverse=True)
    state["scored_candidates"] = scored
    return state


def human_gate_node(state: DiscoveryState) -> DiscoveryState:
    """Prompt the user for feedback to approve or reject profiles, or auto-add if auto_add=True."""
    log.info("[human_gate_node] Processing human gate...")
    scored = state["scored_candidates"]
    threshold = state["threshold"]
    auto_add = state["auto_add"]
    dry_run = state["dry_run"]

    if not scored:
        state["approved_profiles"] = []
        return state

    approved = []

    # Filter candidates meeting the threshold
    high_quality = [c for c in scored if c["relevance_score"] >= threshold]
    low_quality = [c for c in scored if c["relevance_score"] < threshold]

    if auto_add:
        log.info(f"[human_gate_node] Auto-add mode enabled. Adding profiles >= {threshold}")
        print(f"\n[Auto-add] Auto-approving {len(high_quality)} profiles with score >= {threshold}")
        for c in high_quality:
            approved.append({
                "name": c["name"],
                "username": c["username"],
                "profile_url": c["profile_url"],
                "note": f"Auto-discovered (score {c['relevance_score']}/10). Interests: {', '.join(c['matched_interests'])}"
            })
        state["approved_profiles"] = approved
        return state

    if dry_run:
        log.info("[human_gate_node] Dry run mode enabled. Printing candidates without approval prompt.")
        print("\n" + "═"*55)
        print("  Dry Run: Scored Profile Candidates")
        print("═"*55)
        for i, c in enumerate(scored, 1):
            bar = "█" * c["relevance_score"] + "░" * (10 - c["relevance_score"])
            print(f"\n  [{i}] [{bar}] {c['relevance_score']}/10  {c['name']}")
            print(f"      Headline:  {c['headline'][:80]}...")
            print(f"      URL:       {c['profile_url']}")
            print(f"      Topics:    {', '.join(c['matched_interests'])}")
            print(f"      Decision:  {'WOULD ADD' if c['relevance_score'] >= threshold else 'WOULD SKIP'} - {c['skip_reason']}")
        print("\n" + "═"*55)
        state["approved_profiles"] = []
        return state

    # Interactive Human Prompting
    print("\n" + "═"*60)
    print(f"  Profile Discovery Results  ({len(scored)} candidates found)")
    print("═"*60)

    for i, c in enumerate(scored, 1):
        bar = "█" * c["relevance_score"] + "░" * (10 - c["relevance_score"])
        status_label = "HIGH POTENTIAL" if c["relevance_score"] >= threshold else "LOW SIGNAL"
        print(f"\n  [{i}] [{bar}] {c['relevance_score']}/10  {c['name']}  ({status_label})")
        print(f"      Headline: {c['headline'][:90]}")
        print(f"      URL:      {c['profile_url']}")
        if c["matched_interests"]:
            print(f"      Topics:   {', '.join(c['matched_interests'])}")
        print(f"      AI notes: {c['skip_reason']}")

    print("\n" + "─"*60)
    print("  Options:")
    print(f"    [a] Add all profiles scoring >= {threshold}  (Add top {len(high_quality)})")
    print("    [1,2,3...] Enter comma-separated numbers to add specific profiles")
    print("    [n] Skip all / Add none")
    print("    [q] Quit")
    print("─"*60)

    try:
        user_choice = input("\nSelect option: ").strip().lower()
    except (KeyboardInterrupt, EOFError):
        print("\n[i] Operation cancelled.")
        state["approved_profiles"] = []
        return state

    if not user_choice or user_choice == "n":
        print("[i] No profiles approved.")
    elif user_choice == "q":
        print("[i] Exiting.")
        sys.exit(0)
    elif user_choice == "a":
        print(f"[✓] Approved {len(high_quality)} profiles.")
        for c in high_quality:
            approved.append({
                "name": c["name"],
                "username": c["username"],
                "profile_url": c["profile_url"],
                "note": f"Discovered (score {c['relevance_score']}/10). Interests: {', '.join(c['matched_interests'])}"
            })
    else:
        # Parse numbers
        try:
            indices = [int(x.strip()) - 1 for x in user_choice.split(",") if x.strip().isdigit()]
            for idx in indices:
                if 0 <= idx < len(scored):
                    c = scored[idx]
                    approved.append({
                        "name": c["name"],
                        "username": c["username"],
                        "profile_url": c["profile_url"],
                        "note": f"Discovered (score {c['relevance_score']}/10). Interests: {', '.join(c['matched_interests'])}"
                    })
                    print(f"  [+] Approved: {c['name']}")
        except Exception as e:
            print(f"[!] Parsing input failed: {e}. No profiles added.")

    state["approved_profiles"] = approved
    return state


def add_approved_node(state: DiscoveryState) -> DiscoveryState:
    """Commit approved profiles to database memory.db."""
    log.info("[add_approved_node] Committing approved profiles...")
    approved = state["approved_profiles"]
    dry_run = state["dry_run"]

    if not approved:
        state["added_count"] = 0
        return state

    if dry_run:
        log.info(f"[add_approved_node] Dry run - would have added {len(approved)} profiles.")
        state["added_count"] = len(approved)
        return state

    added = 0
    print("\n[->] Saving approved profiles to memory.db...")
    for p in approved:
        try:
            add_person(
                name=p["name"],
                username=p["username"],
                url=p["profile_url"],
                note=p["note"]
            )
            added += 1
            print(f"  [✓] Added: {p['name']} (@{p['username']})")
        except Exception as e:
            log.error(f"[add_approved_node] Failed to add {p['name']}: {e}")
            print(f"  [✗] Failed to add: {p['name']} - {e}")

    state["added_count"] = added
    print(f"\n[✓] Successfully added {added} profiles to watchlist!")
    return state


# ── StateGraph Assembly ────────────────────────────────────────────────────────

def build_graph():
    """Build the LangGraph StateGraph."""
    from langgraph.graph import StateGraph, START, END

    workflow = StateGraph(DiscoveryState)

    # Add nodes
    workflow.add_node("search", search_node)
    workflow.add_node("extract_candidates", extract_candidates_node)
    workflow.add_node("score_candidates", score_candidates_node)
    workflow.add_node("human_gate", human_gate_node)
    workflow.add_node("add_approved", add_approved_node)

    # Define edges
    workflow.add_edge(START, "search")
    workflow.add_edge("search", "extract_candidates")
    
    # Conditional routing after extraction: if no profiles found, route directly to END
    def route_after_extract(state: DiscoveryState):
        if not state["candidate_profiles"]:
            log.info("[route_after_extract] No new candidates found. Routing to END.")
            print("\n[i] No new candidates found. Skipping scoring/approval.")
            return END
        return "score_candidates"

    workflow.add_conditional_edges("extract_candidates", route_after_extract)
    workflow.add_edge("score_candidates", "human_gate")
    workflow.add_edge("human_gate", "add_approved")
    workflow.add_edge("add_approved", END)

    return workflow.compile()


# ── Execution Entry Point ─────────────────────────────────────────────────────

def run_discovery(dry_run: bool = False, auto_add: bool = False, threshold: int = 7) -> int:
    """Run the profile discovery agent end-to-end."""
    if sys.platform == "win32":
        try:
            sys.stdout.reconfigure(encoding="utf-8")
        except AttributeError:
            pass
    initial_state = DiscoveryState(
        search_queries=[],
        raw_search_results=[],
        candidate_profiles=[],
        scored_candidates=[],
        approved_profiles=[],
        added_count=0,
        dry_run=dry_run,
        auto_add=auto_add,
        threshold=threshold,
        errors=[]
    )

    print("\n" + "═"*60)
    print("  LinkedIn Profile Discovery Agent")
    print("  LangGraph-powered search → Gemini scoring → Watchlist add")
    print("═"*60)

    graph = build_graph()
    final_state = graph.invoke(initial_state)

    return final_state["added_count"]


if __name__ == "__main__":
    if sys.platform == "win32":
        try:
            sys.stdout.reconfigure(encoding="utf-8")
        except AttributeError:
            pass
    parser = argparse.ArgumentParser(description="LinkedIn Profile Discovery Agent")
    parser.add_argument("--dry-run", action="store_true", help="Perform search and evaluation without saving to database")
    parser.add_argument("--auto-add", action="store_true", help="Automatically add profiles scoring at or above threshold without prompt")
    parser.add_argument("--threshold", type=int, default=7, help="Relevance score threshold (1-10) for saving/highlighting profiles")
    args = parser.parse_args()

    # Load environment variables if running directly
    from dotenv import load_dotenv
    load_dotenv()

    run_discovery(dry_run=args.dry_run, auto_add=args.auto_add, threshold=args.threshold)
